# Generated by Django 4.2.7 on 2023-11-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_contractor',
            field=models.BooleanField(default=False),
        ),
    ]
