version: '3.3'

services:
  web:
    build: .
    command: >
      sh -c "gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app/

    ports:
      - "8000:8000"
    depends_on:
      - db
      - migration

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: market_db
      POSTGRES_USER: ngrebnev17
      POSTGRES_PASSWORD: 1
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  migration:
    build: .
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate"
    volumes:
      - .:/usr/src/app/
    depends_on:
      - db

volumes:
  postgres_data: