# Generated by Django 4.2.7 on 2023-11-04 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('warranty_type', models.CharField(max_length=100)),
                ('bill_doc', models.CharField(max_length=100)),
                ('tender_name', models.CharField(max_length=100)),
                ('tender_format', models.CharField(max_length=100)),
                ('amount_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('closed_date', models.DateTimeField()),
                ('quality', models.CharField(max_length=100)),
                ('warranty_coverage', models.IntegerField()),
                ('packaging', models.CharField(max_length=100)),
                ('insurance', models.BooleanField(default=False)),
                ('related_service', models.BooleanField(default=False)),
                ('banking_support', models.BooleanField(default=False)),
                ('inspection', models.CharField(max_length=100)),
                ('warranty', models.CharField(max_length=100)),
                ('needed_docs', models.CharField(max_length=100)),
                ('dispute_resolution', models.CharField(max_length=100)),
                ('protocol', models.BigIntegerField()),
                ('advance_payment', models.IntegerField()),
                ('after_shipment', models.IntegerField()),
                ('receive', models.IntegerField()),
                ('payment_date', models.DateTimeField()),
                ('forfeitures_day', models.FloatField()),
                ('forfeitures_max', models.FloatField()),
                ('contractors', models.ManyToManyField(related_name='tenders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
