# Generated by Django 4.2.7 on 2023-11-04 10:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='contractors',
            field=models.ManyToManyField(blank=True, null=True, related_name='tenders', to=settings.AUTH_USER_MODEL),
        ),
    ]
